version: "3"
name: home_server
services:
  traefik:
    image: traefik:v2.9
    container_name: traefik
    restart: always
    command:
      # - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.dashboard.address=:8080"
      - "--api.dashboard=true"
      - "--api.debug=true"
    ports:
      - "80:80"
      - "8080:8080" # Traefik dashboard
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik-dashboard.rule=Host(`traefik.home.com`)"
      - "traefik.http.routers.traefik-dashboard.entrypoints=web"
      - "traefik.http.routers.traefik-dashboard.service=api@internal"

  runner:
    image: gitea/act_runner:latest
    container_name: gitea_act_runner
    restart: always
    depends_on:
      - gitea
    volumes:
      - ./data/act_runner:/data
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - GITEA_RUNNER_REGISTRATION_TOKEN=eYnkjfY876KHKHMa0ntJdxsd6egTRhuoDm17Eihu
      - GITEA_INSTANCE_URL=http://gitea:3000
      - RUNNER_NAME=runner
    networks:
      - web

  gitea:
    image: gitea/gitea:latest
    container_name: gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
    restart: always
    volumes:
      - ${REPO_DIR}/gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3000:3000"
      - "222:22"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.gitea.rule=Host(`gitea.home.com`)"
      - "traefik.http.services.gitea.loadbalancer.server.port=3000"
      - "traefik.http.routers.gitea.entrypoints=web"

  gitea_act:
    image: gitea/act_runner:latest
    container_name: gitea_act_runner
    restart: unless-stopped
    environment:
      - GITEA_RUNNER_REGISTRATION_TOKEN=eYnkjfY876KHKHMa0ntJdxsd6egTRhuoDm17Eihu
      - GITEA_INSTANCE_URL=http://gitea:3000
      - RUNNER_NAME=runner
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${REPO_DIR}:/repo

networks:
  web:
    external: true
