name: Backup config

on:
  schedule:
    - cron:  '5 * * * *'

jobs:
  backup:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: /repo
    steps:
      - name: Backup changes to Gitea
        run: |
          git add -u
          git commit -m "config backup from server"
          git push gitea