name: Backup config

on:
  schedule:
    - cron:  '5 * * * *'

jobs:
  backup:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: /repo
    steps:
      - name: Set git remote if not already set
        run: git remote -v | grep -w gitea || git remote add gitea "./gitea/git/repositories/${GITHUB_REPOSITORY,,}.git"

      - name: Backup changes to Gitea
        run: |
          git add -u
          git commit -m "config backup from server"
          git push gitea